# Generated by Django 3.2.12 on 2024-05-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='lesson',
        ),
    ]
