# Generated by Django 3.2.12 on 2024-05-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20240503_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testattempt',
            old_name='is_correct',
            new_name='is_answer_correct',
        ),
    ]
