# Generated by Django 3.2.12 on 2024-05-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20240512_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=200)),
                ('min_deposit', models.IntegerField()),
                ('link', models.URLField()),
                ('broker_image', models.URLField()),
            ],
        ),
    ]
